### ISSUE TITLE
Bug in Template

### ISSUE THREAD

**Issue by d1b1** [SawyerHood/create-chat-gpt-plugin#1]
yield promises_1.default.cp(path_1.default.resolve(__dirname, ".template"), dir, { recursive: true });
                                 ^

TypeError: promises_1.default.cp is not a function
    at /Users/stephan/.npm/_npx/a67ddc7a09eebd4d/node_modules/create-chat-gpt-plugin/index.js:70:34
    at Generator.throw (<anonymous>)
    at rejected (/Users/stephan/.npm/_npx/a67ddc7a09eebd4d/node_modules/create-chat-gpt-plugin/index.js:7:65

**Comment by d1b1** [comment]
Sorry needed node v18+ got it working
